use_frameworks!

platform :ios, '13.0'

target 'HTTPTaskPublisher_Example' do
  pod 'HTTPTaskPublisher', :path => '../'

  target 'HTTPTaskPublisher_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 7.0.0'
    pod 'Nimble', '~> 12.0.0'
  end
end
