name: test

on:
  pull_request:
    branches:
    - main
  workflow_dispatch:

jobs:
  test:
    name: Testing Pod
    runs-on: macos-14
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v1
      - name: Force XCode 15.1
        run: sudo xcode-select -switch /Applications/Xcode_15.1.app
      - name: Testing Pod Library
        run: bash ./.github/scripts/test_lib.sh
